# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: gibbonos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      # Google Chrome official repo
      files:
        - https://dl.google.com/linux/rpm/stable/x86_64/google-chrome.repo
    install:
      packages:
        - fastfetch
        - steam-devices
        - google-chrome-stable
        # keep dev/container tools
        - toolbox
        - podman
        - skopeo
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - distrobox

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        repos:
          - name: flathub
            url: https://flathub.org/repo/flathub.flatpakrepo
        install:
          - org.gnome.Loupe
      - scope: user

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
